#family:
#  family-name: "happy family"
#  father:
#    name: tom
#    age: 38
#  mother:
#    alias:
#      - rose
#      - alice
#  child:
#    name: jack
#    age: 6
#    friends:
#      - habby: football
#        gender: male
#      - habby: sing
#        gender: female

#指定需要使用的配置文件
server:
  port: 8081